### ISSUE TITLE
Player Using Items

### ISSUE THREAD

**Issue by CalvinOh** [CalvinOh/TERA_Project#10]
Creating the functions that allows the player to use their items. Core gameplay mechanic
- Digging (Shovel)
- Planting (Seed)
- Raking (Covering/Growing) (Rake)
- Watering (Watering Can)
- Harvesting (Shovel)

**Comment by dantogno** [comment]
What the heck does "using items" mean?

**Comment by CalvinOh** [comment]
This was back when we were going to have different tools, and I was making the script that allowed the player to use each tool.
