### ISSUE TITLE
Lack of guide on player actions and outcomes with plants(planting process)

### ISSUE THREAD

**Issue by JieningTao** [CalvinOh/TERA_Project#42]

**Comment by TheQuestCrafter** [comment]
Our resolution to this as discussed between the team and with David is a Tutorial Planet and Context-Based Item Switching for simpler traversal of the gameplay loop.
https://github.com/CalvinOh/TERA_Project/issues/62
https://github.com/CalvinOh/TERA_Project/issues/65
