### ISSUE TITLE
Player Cannot Always Dig a Hole or Plant a Seed

### ISSUE THREAD

**Issue by TheQuestCrafter** [CalvinOh/TERA_Project#76]
In the Planet Alpha Scene, when moving around the planet there are times the player cannot take any actions. I suspect that it is a collider issue. 
1. Dig a hole in the ground
2. Turn 45-60 degrees in either direction
3. Try to dig another hole
4. Instead of digging a hole nothing happens.
When conducting my playtests, this seems to happen multiple ways but turning seems to have the highest frequency of having this bug.

**Comment by CalvinOh** [comment]
Changed hole collider to a trigger collider, added tags to all grass prefabs and code that will ignore any grass prefab. 
Commit: 334af2ca882e4d621e97f9c5c6c04433aa569694
